export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const FETCH_IMAGES = 'FETCH_IMAGES';
export const LOADING_ALBUM = 'LOADING_ALBUM';
export const LOADING_PHOTOS = 'LOADING_PHOTOS';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const FETCH_MORE_IMAGES = 'FETCH_MORE_IMAGES';
export const FILE_FOLDER_IMAGES = 'FILE_FOLDER_IMAGES';
export const CURRENT_DIRECTORY = 'CURRENT_DIRECTORY';